services:
  db:
    image: postgres:16-alpine
    container_name: go-crud-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d root"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - go-crud-network
    restart: unless-stopped

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: go-crud-app
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - DB_URL=postgres://root:root@db:5432/root?sslmode=disable&TimeZone=UTC
    depends_on:
      db:
        condition: service_healthy
    networks:
      - go-crud-network
    restart: on-failure
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local

networks:
  go-crud-network:
    driver: bridge